name: Update ADR Index
on:
  push:
    branches:
      - main
jobs:
  update-adr-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update ADR Index
        run: |
          adr generate toc doc/adr
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add doc/adr/adr-log.md
          git commit -m "Update ADR index"
          git push